name       : sddm-kcm
version    : 5.16.1
release    : 31
source     :
    - https://download.kde.org/stable/plasma/5.16.1/sddm-kcm-5.16.1.tar.xz : 4ff7cf23bd2f132c1cdf122564fdf85934fd268da27f60517bbc0ea02d81c72d
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
