name       : sddm-kcm
version    : 5.27.6
release    : 83
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.6/sddm-kcm-5.27.6.tar.xz : dc70ab178f6954a6aaf7862440a64742c0c600c48f454462e97e09a1ddd6b5e2
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - karchive-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kio-devel
    - knewstuff-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
