name       : sddm-kcm
version    : 5.14.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.0/sddm-kcm-5.14.0.tar.xz : 6d8c5ad18e1bcf8bb42287962a5225ea16203b662935155874cc1387c18fe637
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
