name       : sddm-kcm
version    : 5.16.3
release    : 33
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.3/sddm-kcm-5.16.3.tar.xz : 0fad91b5a7901a42df03113a2277d317ceddf048934f4aa83cd2d735bb9738a3
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
