name       : sddm-kcm
version    : 5.16.4
release    : 34
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.4/sddm-kcm-5.16.4.tar.xz : 340034c5475d751c19c96a75445fa50877fad1c4de3422bc02f4b95e8f14bd68
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
