name       : sddm-kcm
version    : 5.17.2
release    : 37
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.2/sddm-kcm-5.17.2.tar.xz : 29afa561cdd157761d662f3e52226e7b6d8ab6c5fd67bbde073c226ac396e9c1
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
