name       : sddm-kcm
version    : 5.26.4
release    : 79
source     :
    - https://cdn.download.kde.org/stable/plasma/5.26.4/sddm-kcm-5.26.4.tar.xz : cba1d6bb9fdf6bb7afc2d4c0ba15946e3f5b2d9cbdd3a7ada96814e760e714eb
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - karchive-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kio-devel
    - knewstuff-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
