name       : sddm-kcm
version    : 5.10.5
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.10.5/sddm-kcm-5.10.5.tar.xz : 5c2731f34e76fff4c6a228163426a1777f6658fe08284987341af6665769148e
license    : GPL-2.0
component  : desktop.kde.core
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
