name       : sddm-kcm
version    : 5.22.2
release    : 63
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.2.1/sddm-kcm-5.22.2.1.tar.xz : df2d13e23554f73246ea13e419a9774cf011e5258a2bfb324bade0ff7d368981
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - karchive-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kio-devel
    - knewstuff-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
