name       : sddm-kcm
version    : 5.11.2
release    : 3
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.2/sddm-kcm-5.11.2.tar.xz : 2137c3438dce41b79c36f87dfe72533e4c803741d3aca6c57b9ebc33ffe63895
license    : GPL-2.0
component  : desktop.kde.core
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
