name       : sddm-kcm
version    : 5.23.5
release    : 71
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.5/sddm-kcm-5.23.5.tar.xz : bb338657463878b535f73eec6fc32c1f83f0928aeb7e61f66f497044eb0b5233
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - karchive-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kio-devel
    - knewstuff-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
