name       : sddm-kcm
version    : 5.21.5
release    : 61
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.5/sddm-kcm-5.21.5.tar.xz : 5280c8e75167233808d44ce0091f66020a3f8f12590fd9272d3b3fda12ce2d6d
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - karchive-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kio-devel
    - knewstuff-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
